/*----------------------------------------------------------------------

                     This file is part of Freetribe

                https://github.com/bangcorrupt/freetribe

                                License

                   GNU AFFERO GENERAL PUBLIC LICENSE
                      Version 3, 19 November 2007

                           AGPL-3.0-or-later

 Freetribe is free software: you can redistribute it and/or modify it
under the terms of the GNU Affero General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
                  (at your option) any later version.

     Freetribe is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty
        of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
          See the GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>.

                       Copyright bangcorrupt 2023

----------------------------------------------------------------------*/

/**
 * @file    gdb_server.c
 *
 * @brief   GDB command handler & reply generator
 * 
 * @author  vanasoft23 (mvandijk303@gmail.com)
 */

/*----- Includes -----------------------------------------------------*/

#include "ft.h"
#include "str_misc.h"

#if __has_include("gdb_target_xml.h")
#  include "gdb_target_xml.h"
#else
#  error "gdb_target_xml.h" is generated by CMake on successful compile
#endif
	
#include "gdb_monitor.h"
#if 0
#include "gdb_semihosting.h"
#endif
#include "gdb_server.h"

/*----- Types --------------------------------------------------------*/

struct gdb_server {
	gdb_memory_reader_t memory_reader;
	void               *memory_reader_context;
	gdb_memory_writer_t memory_writer;
	void               *memory_writer_context;
};

typedef struct {
	const u8 *cursor;
	const u8 *end;
} monitor_parser_t;

typedef struct {
	const u8 *data;
	u32       length;
} monitor_token_t;

/*----- Globals ------------------------------------------------------*/

gdb_server_t g_gdb_server;

/*----- Static function prototypes -----------------------------------*/

// request handlers

static gdb_command_result_t _handle_stop(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_continue(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_detach(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_step(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_insert_breakpoint(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_remove_breakpoint(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_read_registers(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_read_memory(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_write_memory(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_query(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_monitor_command(
	gdb_server_t       *server,
	const u8           *data,
	u32                 length,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

static gdb_command_result_t _handle_monitor_semihosting(
	gdb_server_t       *server,
	monitor_parser_t   *parser,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);

// reply helpers

static gdb_command_result_t _send_reply(void);
static gdb_command_result_t _reply_empty(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
);
static gdb_command_result_t _reply_error(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply,
	u8                  err_code
);

static bool _reply_put(gdb_reply_writer_t *reply, u8 byte);
static bool _reply_put_str(gdb_reply_writer_t *reply, const char *str);
static bool _reply_put_buf(gdb_reply_writer_t *reply, const u8 *buf, u32 len);

static bool _parse_hex_u32(
	const u8 **cursor,
	const u8  *end,
	u32       *value
);

static void _append_hex_reg(char **pp_data, u32 reg_value);

// monitor command parsing

static bool _monitor_next(
	monitor_parser_t *parser,
	monitor_token_t  *token
);
static void _monitor_skip_whitespace(monitor_parser_t *parser);
static bool _monitor_done(monitor_parser_t *parser);
static bool _monitor_token_equals(
	monitor_token_t token,
	const char     *text
);
static bool _monitor_parse_u32(
	monitor_token_t token,
	u32            *value
);


/*--------------------------------------------------------------------*/
/*                                                                    */
/*                      Public API                                    */
/*                                                                    */
/*--------------------------------------------------------------------*/

void gdb_server_set_memory_reader(
	gdb_server_t       *server,
	gdb_memory_reader_t reader,
	void               *context
) {
	server->memory_reader         = reader;
	server->memory_reader_context = context;
}

void gdb_server_set_memory_writer(
	gdb_server_t       *server,
	gdb_memory_writer_t writer,
	void               *context
) {
	server->memory_writer         = writer;
	server->memory_writer_context = context;
}

/*----- Request parser main ------------------------------------------*/

gdb_command_result_t gdb_server_handle_req(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	reply->len   = 0;
	reply->overflow = false;

	if (request.len == 0) {
		return _reply_empty(server, request, reply);
	}
	
// #ifdef DEBUG
//     static char dbgstr[RSP_TX_CAPACITY];
//     memset(dbgstr, 0, sizeof(dbgstr));
//     memcpy(dbgstr, rsp->tx.payload, rsp->tx.len);
//     DLOG(dbgstr);
// #endif

	char *op = (char*)&request.data[0];

// parse:
	switch (*op) {
	case '?':
		return _handle_stop(server, request, reply);

	case 'c':
		return _handle_continue(server, request, reply);

	case 's':
		return _handle_step(server, request, reply);

	case 'Z':
		return _handle_insert_breakpoint(server, request, reply);

	case 'z':
		return _handle_remove_breakpoint(server, request, reply);

	case 'g':
		return _handle_read_registers(server, request, reply);

	// case 'G':
	//     return _handle_write_registers(server, request, reply);

	// case 'p':
	//     return _handle_read_register(server, request, reply);

	// case 'P':
	//     return _handle_write_register(server, request, reply);

	case 'm':
		return _handle_read_memory(server, request, reply);

	case 'M':
		return _handle_write_memory(server, request, reply);

	// case 'D':
	//     return _handle_detach(server, request, reply);

	case 'q':
		return _handle_query(server, request, reply);

	// case 'Q':
	//     return _handle_set(server, request, reply);

	// case 'v':
	//     return _handle_v_packet(server, request, reply);

	case 'D':
		return _handle_detach(server, request, reply);

	// case 'H': // thread indicator
	//     if (request.len == 1) break; // obligatory edge case prevention
	//     op++;
	//     goto parse;

	default: break;
	}

	// @TODO: handle overflow!!!!!!

	return _reply_empty(server, request, reply);
}

/*--------------------------------------------------------------------*/
/*                                                                    */
/*                      Request handlers                              */
/*                                                                    */
/*--------------------------------------------------------------------*/

/*----- Execution control flow ---------------------------------------*/

static gdb_command_result_t _handle_stop(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	(void)request;

	_reply_put(reply, 'S');
	_reply_put(reply, hex_digit((u8)gdb_monitor_get_stop_reason() >> 4));
	_reply_put(reply, hex_digit((u8)gdb_monitor_get_stop_reason()));

	return _send_reply();
}

static gdb_command_result_t _handle_continue(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	(void)request;
	
	gdb_command_result_t result = {
		.send_reply      = false,
		.action          = GDB_ACTION_CONTINUE,
		.protocol_change = GDB_PROTOCOL_UNCHANGED,
	};
	return result;
}

static gdb_command_result_t _handle_detach(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	(void)request;

	reply->data[0] = 'O';
	reply->data[1] = 'K';
	reply->len     =   2;

	gdb_command_result_t result = {
		.send_reply      = true,
		.action          = GDB_ACTION_DETACH,
		.protocol_change = GDB_PROTOCOL_UNCHANGED,
	};
	return result;
}

static gdb_command_result_t _handle_step(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	(void)request;
	
	if (!gdb_monitor_prepare_step()) {
		return _reply_error(server, request, reply, 1u);
	}

	gdb_command_result_t result = {
		.send_reply      = false,
		.action          = GDB_ACTION_STEP,
		.protocol_change = GDB_PROTOCOL_UNCHANGED,
	};
	return result;
}

static gdb_command_result_t _handle_insert_breakpoint(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	// @TODO: check if watchpoint or breakpoint

	const u8 *cursor = request.data + 1;
	const u8 *end    = request.data + request.len;
	u32       type; // 0 swbreak, 2 write watch, 3 read watch, 4 access watch
	u32       address;
	u32       kind;

	if (!_parse_hex_u32(&cursor, end, &type) ||
		(cursor == end) || (*cursor++ != ',') ||
		!_parse_hex_u32(&cursor, end, &address) ||
		(cursor == end) || (*cursor++ != ',') ||
		!_parse_hex_u32(&cursor, end, &kind) ||
		(cursor != end))
	{
		return _reply_error(server, request, reply, 0x01);
	}
		
	if (kind != 4u) {
		return _reply_error(server, request, reply, 0x01);
	}

	if (type != 0) { // 0 swbreak
		return _reply_error(server, request, reply, 0x01);
	}
	
	if (!gdb_monitor_insert_breakpoint(address)) {
		return _reply_error(server, request, reply, 1u);
	}

	reply->data[0] = 'O';
	reply->data[1] = 'K';
	reply->len     =   2;
	return _send_reply();
}

static gdb_command_result_t _handle_remove_breakpoint(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	// @TODO: check if watchpoint or breakpoint

	const u8 *cursor = request.data + 1;
	const u8 *end    = request.data + request.len;
	u32       type; // 0 swbreak, 2 write watch, 3 read watch, 4 access watch
	u32       address;
	u32       kind;

	if (!_parse_hex_u32(&cursor, end, &type) ||
		(cursor == end) || (*cursor++ != ',') ||
		!_parse_hex_u32(&cursor, end, &address) ||
		(cursor == end) || (*cursor++ != ',') ||
		!_parse_hex_u32(&cursor, end, &kind) ||
		(cursor != end))
	{
		return _reply_error(server, request, reply, 0x01);
	}
		
	if (kind != 4u || (address & 3u) != 0u) {
		return _reply_error(server, request, reply, 0x01);
	}

	if (type != 0) { // 0 swbreak
		return _reply_error(server, request, reply, 0x01);
	}

	if (!gdb_monitor_remove_breakpoint(address)) {
		return _reply_error(server, request, reply, 1u);
	}

	reply->data[0] = 'O';
	reply->data[1] = 'K';
	reply->len     =   2;
	return _send_reply();
}

/*----- Registers ----------------------------------------------------*/

static gdb_command_result_t _handle_read_registers(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {

	if (reply->len + 136 >= reply->capacity) {
		return _reply_empty(server, request, reply);
	}

	char        *data  = (char*)reply->data;
	arm_frame_t *frame = gdb_monitor_read_registers();
	_append_hex_reg(&data, frame->r0);
	_append_hex_reg(&data, frame->r1);
	_append_hex_reg(&data, frame->r2);
	_append_hex_reg(&data, frame->r3);
	_append_hex_reg(&data, frame->r4);
	_append_hex_reg(&data, frame->r5);
	_append_hex_reg(&data, frame->r6);
	_append_hex_reg(&data, frame->r7);
	_append_hex_reg(&data, frame->r8);
	_append_hex_reg(&data, frame->r9);
	_append_hex_reg(&data, frame->r10);
	_append_hex_reg(&data, frame->r11);
	_append_hex_reg(&data, frame->r12);
	_append_hex_reg(&data, frame->sp);
	_append_hex_reg(&data, frame->lr);
	_append_hex_reg(&data, frame->pc);
	_append_hex_reg(&data, frame->cpsr);

	reply->len = 136;

	return _send_reply();

}

static gdb_command_result_t _handle_write_registers(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	
	///  TODO: implement
	
	return _reply_empty(server, request, reply);
}

/*----- Memory -------------------------------------------------------*/

// vibecoded
static gdb_command_result_t _handle_read_memory(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	enum { READ_CHUNK_SIZE = 32 };

	const u8 *cursor = request.data + 1;
	const u8 *end    = request.data + request.len;
	u32       address;
	u32       length;

	if (!_parse_hex_u32(&cursor, end, &address) ||
		(cursor == end) || (*cursor++ != ',') ||
		!_parse_hex_u32(&cursor, end, &length) ||
		(cursor != end)) {
		return _reply_error(server, request, reply, 0x01);
	}

	// Reject address wrap and replies that cannot fit before reading memory.
	if (((length != 0u) && (address > UINT32_MAX - (length - 1u))) ||
		(reply->len > reply->capacity) ||
		(length > (reply->capacity - reply->len) / 2u)) {
		return _reply_error(server, request, reply, 0x22);
	}

	gdb_memory_reader_t reader = server->memory_reader;
	if (reader == NULL) {
		reader = gdb_monitor_read_memory;
	}

	u8  bytes[READ_CHUNK_SIZE];
	u32 offset = 0u;
	while (offset < length) {
		u32 chunk_length = length - offset;
		if (chunk_length > (u32)sizeof(bytes)) {
			chunk_length = (u32)sizeof(bytes);
		}

		if (!reader(
				server->memory_reader_context,
				address + offset,
				bytes,
				chunk_length)) {
			reply->len = 0u;
			return _reply_error(server, request, reply, 0x14);
		}

		for (u32 i = 0u; i < chunk_length; ++i) {
			reply->data[reply->len++] = hex_digit(bytes[i] >> 4);
			reply->data[reply->len++] = hex_digit(bytes[i]);
		}
		offset += chunk_length;
	}

	return _send_reply();
}


// vibecoded
static gdb_command_result_t _handle_write_memory(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	enum { WRITE_CHUNK_SIZE = 32 };

	const u8 *cursor = request.data + 1;
	const u8 *end    = request.data + request.len;
	u32       address;
	u32       length;

	if (!_parse_hex_u32(&cursor, end, &address) ||
		(cursor == end) || (*cursor++ != ',') ||
		!_parse_hex_u32(&cursor, end, &length) ||
		(cursor == end) || (*cursor++ != ':')) {
		return _reply_error(server, request, reply, 0x01);
	}

	u32 encoded_length = (u32)(end - cursor);
	if (((encoded_length & 1u) != 0u) ||
		((encoded_length / 2u) != length)) {
		return _reply_error(server, request, reply, 0x01);
	}

	/* Validate every digit before allowing the first memory write. */
	for (const u8 *digit = cursor; digit < end; ++digit) {
		if (hex_nibble(*digit) < 0) {
			return _reply_error(server, request, reply, 0x01);
		}
	}

	if ((length != 0u) && (address > UINT32_MAX - (length - 1u))) {
		return _reply_error(server, request, reply, 0x22);
	}

	/* Do not modify memory when even the success response cannot fit. */
	if (reply->capacity < 2u) {
		reply->overflow = true;
		return _send_reply();
	}

	gdb_memory_writer_t writer = server->memory_writer;
	if (writer == NULL) {
		writer = gdb_monitor_write_memory;
	}

	u8  bytes[WRITE_CHUNK_SIZE];
	u32 offset = 0u;
	while (offset < length) {
		u32 chunk_length = length - offset;
		if (chunk_length > (u32)sizeof(bytes)) {
			chunk_length = (u32)sizeof(bytes);
		}

		for (u32 i = 0u; i < chunk_length; ++i) {
			u32 encoded_offset = (offset + i) * 2u;
			bytes[i] = (u8)(
				(hex_nibble(cursor[encoded_offset]) << 4) |
				hex_nibble(cursor[encoded_offset + 1u])
			);
		}

		if (!writer(
				server->memory_writer_context,
				address + offset,
				bytes,
				chunk_length)) {
			return _reply_error(server, request, reply, 0x14);
		}
		offset += chunk_length;
	}

	_reply_put_str(reply, "OK");
	return _send_reply();
}

/*----- Miscellaneous ------------------------------------------------*/

static gdb_command_result_t _handle_query(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	if (buf_starts_with_cstr(request.data, request.len, "qSupported")) {

		const char *str = "PacketSize=4000;qXfer:features:read+";
		_reply_put_str(reply, str);

	}
	else if (buf_starts_with_cstr(request.data, request.len, "qXfer:features:read:target.xml")) {

		_reply_put(reply, 'l');
		_reply_put_buf(reply, gdb_target_xml, gdb_target_xml_len);

	} else if (buf_starts_with_cstr(request.data, request.len, "qRcmd")) {
		
		const u8 *cursor = request.data + 5;
		const u8 *end    = request.data + request.len;

		if ((cursor == end)   ||
			(*cursor++ != ',') ||
			(cursor == end)) {
			return _reply_error(server, request, reply, 0x01);
		}

		u32 encoded_length = (u32)(end - cursor);
		if (((encoded_length & 1u) != 0u) ||
			((encoded_length / 2u) > reply->capacity)) {
			return _reply_error(server, request, reply, 0x01);
		}

		u32 decoded_length = encoded_length / 2u;
		for (u32 i = 0u; i < decoded_length; ++i) {
			int high = hex_nibble(cursor[i * 2u]);
			int low  = hex_nibble(cursor[i * 2u + 1u]);
			if ((high < 0) || (low < 0)) {
				return _reply_error(server, request, reply, 0x01);
			}

			reply->data[i] = (u8)((high << 4) | low);
		}

		return _handle_monitor_command(
			server,
			reply->data,
			decoded_length,
			request,
			reply
		);
	}

	return _send_reply();
}



static gdb_command_result_t _handle_monitor_command(
	gdb_server_t       *server,
	const u8           *data,
	u32                 length,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	monitor_parser_t parser = {
		.cursor = data,
		.end    = data + length,
	};

	monitor_token_t command;

	if (!_monitor_next(&parser, &command)) {
		return _reply_error(server, request, reply, 0x01);
	}

	if (_monitor_token_equals(command, "boot")) {
		if (!_monitor_done(&parser)) {
			return _reply_error(server, request, reply, 0x01);
		}

		_reply_put_str(reply, "OK");
		gdb_command_result_t result = _send_reply();
		result.action = GDB_ACTION_HANDOFF;
		return result;
	}

#if 0
	if (_monitor_token_equals(command, "semihosting")) {
		return _handle_monitor_semihosting(
			server, &parser, request, reply
		);
	}
#endif

	return _reply_error(server, request, reply, 0x01);
}


#if 0
static gdb_command_result_t _handle_monitor_semihosting(
	gdb_server_t       *server,
	monitor_parser_t   *parser,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	monitor_token_t operation;
	monitor_token_t argument;
	u32 value;

	if (!_monitor_next(parser, &operation) ||
		!_monitor_next(parser, &argument) ||
		!_monitor_done(parser) ||
		!_monitor_parse_u32(argument, &value)) {
		return _reply_error(server, request, reply, 0x01);
	}

	if (_monitor_token_equals(operation, "enable")) {
		if (!gdb_semihosting_enable(value)) {
			return _reply_error(server, request, reply, 0x01);
		}

	} else if (_monitor_token_equals(operation, "IOClient")) {
		if (!gdb_semihosting_set_io_client(value)) {
			return _reply_error(server, request, reply, 0x01);
		}

	} else {
		return _reply_error(server, request, reply, 0x01);
	}

	_reply_put_str(reply, "OK");
	return _send_reply();
}
#endif


/*--------------------------------------------------------------------*/
/*                                                                    */
/*                      Reply helpers                                 */
/*                                                                    */
/*--------------------------------------------------------------------*/

static gdb_command_result_t _reply_empty(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply
) {
	(void)server;
	(void)request;
	reply->len = 0;
	return _send_reply();
}

static gdb_command_result_t _send_reply(void) {
	gdb_command_result_t result = {
		.send_reply      = true,
		.action          = GDB_ACTION_NONE,
		.protocol_change = GDB_PROTOCOL_UNCHANGED,
	};
	return result;
}

static gdb_command_result_t _reply_error(
	gdb_server_t       *server,
	gdb_request_t       request,
	gdb_reply_writer_t *reply,
	u8                  err_code
) {
	(void)server;
	(void)request;

	if (reply->capacity < 3u) {
		reply->len      = 0u;
		reply->overflow = true;
		return _send_reply();
	}

	reply->len  = 3;
	reply->data[0] = 'E';
	reply->data[1] = hex_digit(err_code >> 4);
	reply->data[2] = hex_digit(err_code);
	return _send_reply();
}

/*--------------------------------------------------------------------*/

static bool _reply_put(gdb_reply_writer_t *reply, u8 byte) {

	if (reply->len >= reply->capacity) {
		reply->overflow = true;
		reply->len = 0;
		return false;
	}

	reply->data[reply->len++] = byte;
	return true;
}

static bool _reply_put_buf(gdb_reply_writer_t *reply, const u8 *buf, u32 len) {
	
	if ((reply->len > reply->capacity) ||
		(len > reply->capacity - reply->len)) {
		reply->overflow = true;
		reply->len = 0;
		return false;
	}

	memcpy(reply->data + reply->len, buf, len);
	reply->len += len;

	return true;
}

static bool _reply_put_str(gdb_reply_writer_t *reply, const char *str) {
	
	return _reply_put_buf(reply, (const u8*)str, strlen(str));
}

static void _append_hex_reg(char **pp_data, u32 reg_value) {
	hex_digits32(*pp_data, reg_value);
	*pp_data += 8;
}

static bool _parse_hex_u32(
	const u8 **cursor,
	const u8  *end,
	u32       *value
) {
	const u8 *position = *cursor;
	u32       parsed   = 0u;
	bool      has_digit = false;

	while (position < end) {
		int nibble = hex_nibble(*position);
		if (nibble < 0) {
			break;
		}
		if (parsed > (UINT32_MAX >> 4)) {
			return false;
		}
		parsed = (parsed << 4) | (u32)nibble;
		position++;
		has_digit = true;
	}

	if (!has_digit) {
		return false;
	}

	*cursor = position;
	*value  = parsed;
	return true;
}

/*--------------------------------------------------------------------*/

static bool _monitor_next(
	monitor_parser_t *parser,
	monitor_token_t  *token
) {
	_monitor_skip_whitespace(parser);

	if (parser->cursor == parser->end) {
		return false;
	}

	const u8 *start = parser->cursor;
	while ((parser->cursor < parser->end) &&
		   (*parser->cursor != ' ') && (*parser->cursor != '\t')) {
		parser->cursor++;
	}

	token->data   = start;
	token->length = (u32)(parser->cursor - start);
	return true;
}

static void _monitor_skip_whitespace(monitor_parser_t *parser) {
	while ((parser->cursor < parser->end) &&
		   ((*parser->cursor == ' ') || (*parser->cursor == '\t'))) {
		parser->cursor++;
	}
}

static bool _monitor_done(monitor_parser_t *parser) {
	_monitor_skip_whitespace(parser);
	return parser->cursor == parser->end;
}

static bool _monitor_token_equals(
	monitor_token_t token,
	const char     *text
) {
	size_t text_length = strlen(text);
	return (text_length == token.length) &&
		   (memcmp(token.data, text, text_length) == 0);
}

static bool _monitor_parse_u32(
	monitor_token_t token,
	u32            *value
) {
	u32 position = 0u;
	u32 base     = 10u;
	u32 parsed   = 0u;

	if (token.length == 0u) {
		return false;
	}

	if ((token.length >= 2u) &&
		(token.data[0] == '0') &&
		((token.data[1] == 'x') || (token.data[1] == 'X'))) {
		position = 2u;
		base     = 16u;
	}

	if (position == token.length) {
		return false;
	}

	for (; position < token.length; ++position) {
		int digit = hex_nibble(token.data[position]);
		if ((digit < 0) || ((u32)digit >= base)) {
			return false;
		}

		if (parsed > (UINT32_MAX - (u32)digit) / base) {
			return false;
		}
		parsed = parsed * base + (u32)digit;
	}

	*value = parsed;
	return true;
}


/*----- End of file --------------------------------------------------*/
